version: 2.1
jobs:
  hello-world:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: "Hello World"
          command:
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

workflows:
  hello-world-workflow:
    jobs:
      - hello-world